### ISSUE TITLE
My bad, sorry.

### ISSUE THREAD

**Issue by gunsmithfiamma** [qba667/MAVLinkToIbus#1]
Excuse me if I'm asking this, but my english is not very good as it's used to be.
I cannot quite understand this passage in the readme:
"After downloading of AltSoftSerial lib configuration for ARDUINO_AVR_YUN, ARDUINO_AVR_LEONARDO and AVR_ATmega32U4 must be replaced with definitions provided in MAVLinkTelemetry.h line 18. As input capture pin 4 must be used and as output compare pin 9 must be used"
Can you explain it more accurately?
Of course, if I'm not asking too much.
My best regards 
Francesco

**Comment by qba667** [comment]
@gunsmithfiamma 
I will write later in more details what must be changed (files, lines etc).
Maybe also sensor list must be updated because last I6 FW is changes a little.

**Comment by gunsmithfiamma** [comment]
Thank you very much .

**Comment by qba667** [comment]
@gunsmithfiamma readme updated

**Comment by gunsmithfiamma** [comment]
@qba667 Thank you very much my friend, this is really appreciated

**Comment by qba667** [comment]
@gunsmithfiamma let me know if it is working es expected - please use latest fw for I6 - the best source is rcgorups topic. Keep in mind that you need to enable desired sensors in source before compiling. During weekend I will try to synchronize the sensors with TX fw.

**Comment by qba667** [comment]
@gunsmithfiamma were you able to make it working? I am working on next version where all sensors implemented in FW of i6 will be send. I will keep you updated.

**Comment by gunsmithfiamma** [comment]
@qba667 Didn't have the time to test it yet, because my IA6b got damaged after a crash (one esc burned during a loiter test and the quad fell from 40m).
Waiting for a new one to arrive.
