### ISSUE TITLE
Explain please iBus and telemetry on same wire

### ISSUE THREAD

**Issue by DimaVIII** [qba667/MAVLinkToIbus#3]
"There is also version sending IBus channel data and telemetry on same wire (serial port)"

Can you please explain a bit more how this should work.

If I get it to work I will write you up a little tutorial with pictures that you can add to Github so other people can benefit from your awesome work.

EDIT: Do you mean this setup? https://github.com/betaflight/betaflight/wiki/Ibus-telemetry

**Comment by qba667** [comment]
@DimaVIII 
Even more there is one version allowing using single wire without any additional hardware - I have just forwarded channel data on same port.
